---
- name: Deploy 3Tier Application
  hosts: all
  gather_facts: no
  become: true

  pre_tasks:
    - name: pre-configure all hosts with repos
      template:
        src: ./open_three-tier-app.repo
        dest: /etc/yum.repos.d/open_three-tier-app.repo
        mode: 0644

- name: deploy haproxy
  hosts: frontends
  gather_facts: no
  become: true
  
  roles:
    - haproxy
#    - tomcat
#    - configure_app1
#    - postgres
#    - apache
